require 'spec_helper'

describe "requests/edit.html.haml" do
  before(:each) do
    @request = assign(:request, stub_model(Request,
      :item => "MyString",
      :cargo_classification_id => 1,
      :weight => "9.99",
      :volume => "9.99",
      :temperature => 1,
      :evropallet => 1,
      :bigpallet => 1,
      :belts_count => 1,
      :height => "9.99",
      :width => "9.99",
      :length => "9.99",
      :loading_up => false,
      :loading_down => false,
      :loading_side => false,
      :crate_body => 1,
      :customer_company_id => 1,
      :carrier_company_id => 1,
      :driver_id => 1,
      :car_id => 1,
      :cars_count => 1,
      :carrier_rate_summ => "9.99",
      :carrier_rate_podacha_hours => 1,
      :carrier_rate_hour_price => "9.99",
      :carrier_dop_prab_price => "9.99",
      :carrier_dop_prab_count => "9.99",
      :carrier_dop_prab_summ => "9.99",
      :carrier_dop_prostoy_price => "9.99",
      :carrier_dop_prostoy_count => 1,
      :carrier_dop_prostoy_summ => "9.99",
      :carrier_dop_dop_tochka_pogr_price => "9.99",
      :carrier_dop_dop_tochka_pogr_count => 1,
      :carrier_dop_dop_tochka_pogr_summ => "9.99",
      :carrier_dop_dop_tochka_razgr_price => "9.99",
      :carrier_dop_dop_tochka_razgr_count => 1,
      :carrier_dop_dop_tochka_razgr_summ => "9.99",
      :carrier_dop_vozvr_price => "9.99",
      :carrier_dop_vozvr_count => 1,
      :carrier_dop_vozvr_summ => "9.99",
      :carrier_dop_pereg_price => "9.99",
      :carrier_dop_pereg_count => "9.99",
      :carrier_dop_pereg_summ => "9.99",
      :carrier_dop_night_stay_price => "9.99",
      :carrier_dop_night_stay_count => 1,
      :carrier_dop_night_stay_summ => "9.99",
      :carrier_dop_mezgorod_price => "9.99",
      :carrier_dop_mezgorod_count => 1,
      :carrier_dop_mezgorod_summ => "9.99",
      :carrier_dop_rastentovka_price => "9.99",
      :carrier_dop_rastentovka_count => 1,
      :carrier_dop_rastentovka_summ => "9.99",
      :carrier_dop_soprov_price => "9.99",
      :carrier_dop_soprov_count => 1,
      :carrier_dop_soprov_summ => "9.99",
      :carrier_dop_negabarit_price => "9.99",
      :carrier_dop_negabarit_count => 1,
      :carrier_dop_negabarit_summ => "9.99",
      :carrier_dop_gruzch_price => "9.99",
      :carrier_dop_gruzch_count => 1,
      :carrier_dop_gruzch_summ => "9.99",
      :carrier_dop_summ => "9.99",
      :carrier_total_summ => "9.99",
      :carrier_rate_hours => 1,
      :carrier_rate_sverh_price => "9.99",
      :carrier_rate_sverh_count => 1,
      :carrier_rate_sverh_summ => "9.99",
      :carrier_rate_total_summ => "9.99",
      :carrier_dop_discount => "9.99",
      :carrier_summ => "9.99",
      :carrier_total_summ => "9.99",
      :carrier_summ_to_pay => "9.99",
      :carrier_prepayment => "9.99",
      :carrier_payment_method_id => 1,
      :carrier_payment_way_id => 1,
      :carrier_maturity => 1,
      :carrier_payment_docs_id => 1,
      :carrier_documents_return_term => 1,
      :customer_rate_summ => "9.99",
      :customer_rate_podacha_hours => 1,
      :customer_rate_hour_price => "9.99",
      :customer_dop_summ => "9.99",
      :customer_rate_hours => 1,
      :customer_rate_sverh_price => "9.99",
      :customer_rate_sverh_count => 1,
      :customer_rate_sverh_summ => "9.99",
      :customer_rate_total_summ => "9.99",
      :customer_dop_prab_price => "9.99",
      :customer_dop_prab_count => "9.99",
      :customer_dop_prab_summ => "9.99",
      :customer_dop_dop_tochka_pogr_price => "9.99",
      :customer_dop_dop_tochka_pogr_count => 1,
      :customer_dop_dop_tochka_pogr_summ => "9.99",
      :customer_dop_dop_tochka_razgr_price => "9.99",
      :customer_dop_dop_tochka_razgr_count => 1,
      :customer_dop_dop_tochka_razgr_summ => "9.99",
      :customer_dop_vozvr_price => "9.99",
      :customer_dop_vozvr_count => 1,
      :customer_dop_vozvr_summ => "9.99",
      :customer_dop_pereg_price => "9.99",
      :customer_dop_pereg_count => "9.99",
      :customer_dop_pereg_summ => "9.99",
      :customer_dop_night_stay_price => "9.99",
      :customer_dop_night_stay_count => 1,
      :customer_dop_night_stay_summ => "9.99",
      :customer_dop_mezgorod_price => "9.99",
      :customer_dop_mezgorod_count => 1,
      :customer_dop_mezgorod_summ => "9.99",
      :customer_dop_rastentovka_price => "9.99",
      :customer_dop_rastentovka_count => 1,
      :customer_dop_rastentovka_summ => "9.99",
      :customer_dop_soprov_price => "9.99",
      :customer_dop_soprov_count => 1,
      :customer_dop_soprov_summ => "9.99",
      :customer_dop_negabarit_price => "9.99",
      :customer_dop_negabarit_count => 1,
      :customer_dop_negabarit_summ => "9.99",
      :customer_dop_gruzch_price => "9.99",
      :customer_dop_gruzch_count => 1,
      :customer_dop_gruzch_summ => "9.99",
      :customer_total_summ => "9.99",
      :customer_summ_to_pay => "9.99",
      :customer_invoice_number => "MyString",
      :customer_payed_summ => "9.99",
      :customer_prepayment => "9.99",
      :customer_payment_method_id => 1,
      :customer_payment_way_id => 1,
      :customer_maturity => 1,
      :customer_payment_doc_id => 1,
      :customer_documents_return_term => 1,
      :user_id => 1,
      :manager_fot => "MyString",
      :manager_percent => "9.99",
      :manager_premium => "9.99",
      :manager_total_summ => "9.99",
      :account_expenditure => 1,
      :account_money => "MyString",
      :account_parish_summ => "9.99",
      :account_consumption_respect => 1,
      :account_consumption_summ => "9.99",
      :responsibility_transport_replacement_requirement => "MyString",
      :compensation_for_damage => "MyString",
      :undeliver_transport_loading_city => "MyString",
      :undeliver_transport_loading_intercity => "MyString",
      :transport_late_loading_city => "MyString",
      :transport_late_loading_intercity => "MyString",
      :transport_late_destination_city => "MyString",
      :transport_late_destination_intercity => "MyString",
      :transport_refuse_loading_day_city => "MyString",
      :transport_refuse_loading_day_intercity => "MyString",
      :transport_idle_excessively_city => "MyString",
      :transport_idle_excessively_intercity => "MyString",
      :payment_late => "MyString",
      :document_late => "MyString",
      :customer_responsibility_car_deny_price => "9.99",
      :customer_responsibility_car_deny_summ => "9.99",
      :customer_responsibility_prostoy_count => "MyString",
      :customer_responsibility_prostoy_price => "9.99",
      :customer_responsibility_prostoy_summ => "9.99",
      :customer_responsibility_payment_late_count => "MyString",
      :customer_responsibility_payment_late_price => "9.99",
      :customer_responsibility_payment_late_summ => "9.99",
      :customer_responsibility_document_late_count => "MyString",
      :customer_responsibility_document_late_price => "MyString",
      :customer_responsibility_document_late_summ => "MyString",
      :carrier_responsibility_car_deny_price => "MyString",
      :carrier_responsibility_car_deny_summ => "MyString",
      :carrier_responsibility_late_count => "MyString",
      :carrier_responsibility_late_price => "MyString",
      :carrier_responsibility_late_summ => "MyString",
      :carrier_responsibility_delivery_late_count => "MyString",
      :carrier_responsibility_delivery_late_price => "MyString",
      :carrier_responsibility_delivery_late_summ => "MyString",
      :carrier_responsibility_document_late_count => "MyString",
      :carrier_responsibility_document_late_price => "MyString",
      :carrier_responsibility_document_late_summ => "MyString",
      :carrier_responsibility_summ => "MyString",
      :customer_responsibility_summ => "MyString",
      :transport_idle_excessively_hours => "MyString",
      :transport_late_loading_hours => "MyString",
      :transport_late_destination_hours => "MyString",
      :request_type => "MyString",
      :other_conditions => "MyString",
      :carrier_rate_total_summ => "9.99",
      :customer_rate_total_summ => "9.99",
      :bill_id => 1,
      :is_finished => false,
      :customer_payment_way_for_salary => "MyString",
      :carrier_payment_way_for_salary => "MyString"
    ))
  end

  it "renders the edit request form" do
    render

    # Run the generator again with the --webrat flag if you want to use webrat matchers
    assert_select "form", :action => requests_path(@request), :method => "post" do
      assert_select "input#request_item", :name => "request[item]"
      assert_select "input#request_cargo_classification_id", :name => "request[cargo_classification_id]"
      assert_select "input#request_weight", :name => "request[weight]"
      assert_select "input#request_volume", :name => "request[volume]"
      assert_select "input#request_temperature", :name => "request[temperature]"
      assert_select "input#request_evropallet", :name => "request[evropallet]"
      assert_select "input#request_bigpallet", :name => "request[bigpallet]"
      assert_select "input#request_belts_count", :name => "request[belts_count]"
      assert_select "input#request_height", :name => "request[height]"
      assert_select "input#request_width", :name => "request[width]"
      assert_select "input#request_length", :name => "request[length]"
      assert_select "input#request_loading_up", :name => "request[loading_up]"
      assert_select "input#request_loading_down", :name => "request[loading_down]"
      assert_select "input#request_loading_side", :name => "request[loading_side]"
      assert_select "input#request_crate_body", :name => "request[crate_body]"
      assert_select "input#request_customer_company_id", :name => "request[customer_company_id]"
      assert_select "input#request_carrier_company_id", :name => "request[carrier_company_id]"
      assert_select "input#request_driver_id", :name => "request[driver_id]"
      assert_select "input#request_car_id", :name => "request[car_id]"
      assert_select "input#request_cars_count", :name => "request[cars_count]"
      assert_select "input#request_carrier_rate_summ", :name => "request[carrier_rate_summ]"
      assert_select "input#request_carrier_rate_podacha_hours", :name => "request[carrier_rate_podacha_hours]"
      assert_select "input#request_carrier_rate_hour_price", :name => "request[carrier_rate_hour_price]"
      assert_select "input#request_carrier_dop_prab_price", :name => "request[carrier_dop_prab_price]"
      assert_select "input#request_carrier_dop_prab_count", :name => "request[carrier_dop_prab_count]"
      assert_select "input#request_carrier_dop_prab_summ", :name => "request[carrier_dop_prab_summ]"
      assert_select "input#request_carrier_dop_prostoy_price", :name => "request[carrier_dop_prostoy_price]"
      assert_select "input#request_carrier_dop_prostoy_count", :name => "request[carrier_dop_prostoy_count]"
      assert_select "input#request_carrier_dop_prostoy_summ", :name => "request[carrier_dop_prostoy_summ]"
      assert_select "input#request_carrier_dop_dop_tochka_pogr_price", :name => "request[carrier_dop_dop_tochka_pogr_price]"
      assert_select "input#request_carrier_dop_dop_tochka_pogr_count", :name => "request[carrier_dop_dop_tochka_pogr_count]"
      assert_select "input#request_carrier_dop_dop_tochka_pogr_summ", :name => "request[carrier_dop_dop_tochka_pogr_summ]"
      assert_select "input#request_carrier_dop_dop_tochka_razgr_price", :name => "request[carrier_dop_dop_tochka_razgr_price]"
      assert_select "input#request_carrier_dop_dop_tochka_razgr_count", :name => "request[carrier_dop_dop_tochka_razgr_count]"
      assert_select "input#request_carrier_dop_dop_tochka_razgr_summ", :name => "request[carrier_dop_dop_tochka_razgr_summ]"
      assert_select "input#request_carrier_dop_vozvr_price", :name => "request[carrier_dop_vozvr_price]"
      assert_select "input#request_carrier_dop_vozvr_count", :name => "request[carrier_dop_vozvr_count]"
      assert_select "input#request_carrier_dop_vozvr_summ", :name => "request[carrier_dop_vozvr_summ]"
      assert_select "input#request_carrier_dop_pereg_price", :name => "request[carrier_dop_pereg_price]"
      assert_select "input#request_carrier_dop_pereg_count", :name => "request[carrier_dop_pereg_count]"
      assert_select "input#request_carrier_dop_pereg_summ", :name => "request[carrier_dop_pereg_summ]"
      assert_select "input#request_carrier_dop_night_stay_price", :name => "request[carrier_dop_night_stay_price]"
      assert_select "input#request_carrier_dop_night_stay_count", :name => "request[carrier_dop_night_stay_count]"
      assert_select "input#request_carrier_dop_night_stay_summ", :name => "request[carrier_dop_night_stay_summ]"
      assert_select "input#request_carrier_dop_mezgorod_price", :name => "request[carrier_dop_mezgorod_price]"
      assert_select "input#request_carrier_dop_mezgorod_count", :name => "request[carrier_dop_mezgorod_count]"
      assert_select "input#request_carrier_dop_mezgorod_summ", :name => "request[carrier_dop_mezgorod_summ]"
      assert_select "input#request_carrier_dop_rastentovka_price", :name => "request[carrier_dop_rastentovka_price]"
      assert_select "input#request_carrier_dop_rastentovka_count", :name => "request[carrier_dop_rastentovka_count]"
      assert_select "input#request_carrier_dop_rastentovka_summ", :name => "request[carrier_dop_rastentovka_summ]"
      assert_select "input#request_carrier_dop_soprov_price", :name => "request[carrier_dop_soprov_price]"
      assert_select "input#request_carrier_dop_soprov_count", :name => "request[carrier_dop_soprov_count]"
      assert_select "input#request_carrier_dop_soprov_summ", :name => "request[carrier_dop_soprov_summ]"
      assert_select "input#request_carrier_dop_negabarit_price", :name => "request[carrier_dop_negabarit_price]"
      assert_select "input#request_carrier_dop_negabarit_count", :name => "request[carrier_dop_negabarit_count]"
      assert_select "input#request_carrier_dop_negabarit_summ", :name => "request[carrier_dop_negabarit_summ]"
      assert_select "input#request_carrier_dop_gruzch_price", :name => "request[carrier_dop_gruzch_price]"
      assert_select "input#request_carrier_dop_gruzch_count", :name => "request[carrier_dop_gruzch_count]"
      assert_select "input#request_carrier_dop_gruzch_summ", :name => "request[carrier_dop_gruzch_summ]"
      assert_select "input#request_carrier_dop_summ", :name => "request[carrier_dop_summ]"
      assert_select "input#request_carrier_total_summ", :name => "request[carrier_total_summ]"
      assert_select "input#request_carrier_rate_hours", :name => "request[carrier_rate_hours]"
      assert_select "input#request_carrier_rate_sverh_price", :name => "request[carrier_rate_sverh_price]"
      assert_select "input#request_carrier_rate_sverh_count", :name => "request[carrier_rate_sverh_count]"
      assert_select "input#request_carrier_rate_sverh_summ", :name => "request[carrier_rate_sverh_summ]"
      assert_select "input#request_carrier_rate_total_summ", :name => "request[carrier_rate_total_summ]"
      assert_select "input#request_carrier_dop_discount", :name => "request[carrier_dop_discount]"
      assert_select "input#request_carrier_summ", :name => "request[carrier_summ]"
      assert_select "input#request_carrier_total_summ", :name => "request[carrier_total_summ]"
      assert_select "input#request_carrier_summ_to_pay", :name => "request[carrier_summ_to_pay]"
      assert_select "input#request_carrier_prepayment", :name => "request[carrier_prepayment]"
      assert_select "input#request_carrier_payment_method_id", :name => "request[carrier_payment_method_id]"
      assert_select "input#request_carrier_payment_way_id", :name => "request[carrier_payment_way_id]"
      assert_select "input#request_carrier_maturity", :name => "request[carrier_maturity]"
      assert_select "input#request_carrier_payment_docs_id", :name => "request[carrier_payment_docs_id]"
      assert_select "input#request_carrier_documents_return_term", :name => "request[carrier_documents_return_term]"
      assert_select "input#request_customer_rate_summ", :name => "request[customer_rate_summ]"
      assert_select "input#request_customer_rate_podacha_hours", :name => "request[customer_rate_podacha_hours]"
      assert_select "input#request_customer_rate_hour_price", :name => "request[customer_rate_hour_price]"
      assert_select "input#request_customer_dop_summ", :name => "request[customer_dop_summ]"
      assert_select "input#request_customer_rate_hours", :name => "request[customer_rate_hours]"
      assert_select "input#request_customer_rate_sverh_price", :name => "request[customer_rate_sverh_price]"
      assert_select "input#request_customer_rate_sverh_count", :name => "request[customer_rate_sverh_count]"
      assert_select "input#request_customer_rate_sverh_summ", :name => "request[customer_rate_sverh_summ]"
      assert_select "input#request_customer_rate_total_summ", :name => "request[customer_rate_total_summ]"
      assert_select "input#request_customer_dop_prab_price", :name => "request[customer_dop_prab_price]"
      assert_select "input#request_customer_dop_prab_count", :name => "request[customer_dop_prab_count]"
      assert_select "input#request_customer_dop_prab_summ", :name => "request[customer_dop_prab_summ]"
      assert_select "input#request_customer_dop_dop_tochka_pogr_price", :name => "request[customer_dop_dop_tochka_pogr_price]"
      assert_select "input#request_customer_dop_dop_tochka_pogr_count", :name => "request[customer_dop_dop_tochka_pogr_count]"
      assert_select "input#request_customer_dop_dop_tochka_pogr_summ", :name => "request[customer_dop_dop_tochka_pogr_summ]"
      assert_select "input#request_customer_dop_dop_tochka_razgr_price", :name => "request[customer_dop_dop_tochka_razgr_price]"
      assert_select "input#request_customer_dop_dop_tochka_razgr_count", :name => "request[customer_dop_dop_tochka_razgr_count]"
      assert_select "input#request_customer_dop_dop_tochka_razgr_summ", :name => "request[customer_dop_dop_tochka_razgr_summ]"
      assert_select "input#request_customer_dop_vozvr_price", :name => "request[customer_dop_vozvr_price]"
      assert_select "input#request_customer_dop_vozvr_count", :name => "request[customer_dop_vozvr_count]"
      assert_select "input#request_customer_dop_vozvr_summ", :name => "request[customer_dop_vozvr_summ]"
      assert_select "input#request_customer_dop_pereg_price", :name => "request[customer_dop_pereg_price]"
      assert_select "input#request_customer_dop_pereg_count", :name => "request[customer_dop_pereg_count]"
      assert_select "input#request_customer_dop_pereg_summ", :name => "request[customer_dop_pereg_summ]"
      assert_select "input#request_customer_dop_night_stay_price", :name => "request[customer_dop_night_stay_price]"
      assert_select "input#request_customer_dop_night_stay_count", :name => "request[customer_dop_night_stay_count]"
      assert_select "input#request_customer_dop_night_stay_summ", :name => "request[customer_dop_night_stay_summ]"
      assert_select "input#request_customer_dop_mezgorod_price", :name => "request[customer_dop_mezgorod_price]"
      assert_select "input#request_customer_dop_mezgorod_count", :name => "request[customer_dop_mezgorod_count]"
      assert_select "input#request_customer_dop_mezgorod_summ", :name => "request[customer_dop_mezgorod_summ]"
      assert_select "input#request_customer_dop_rastentovka_price", :name => "request[customer_dop_rastentovka_price]"
      assert_select "input#request_customer_dop_rastentovka_count", :name => "request[customer_dop_rastentovka_count]"
      assert_select "input#request_customer_dop_rastentovka_summ", :name => "request[customer_dop_rastentovka_summ]"
      assert_select "input#request_customer_dop_soprov_price", :name => "request[customer_dop_soprov_price]"
      assert_select "input#request_customer_dop_soprov_count", :name => "request[customer_dop_soprov_count]"
      assert_select "input#request_customer_dop_soprov_summ", :name => "request[customer_dop_soprov_summ]"
      assert_select "input#request_customer_dop_negabarit_price", :name => "request[customer_dop_negabarit_price]"
      assert_select "input#request_customer_dop_negabarit_count", :name => "request[customer_dop_negabarit_count]"
      assert_select "input#request_customer_dop_negabarit_summ", :name => "request[customer_dop_negabarit_summ]"
      assert_select "input#request_customer_dop_gruzch_price", :name => "request[customer_dop_gruzch_price]"
      assert_select "input#request_customer_dop_gruzch_count", :name => "request[customer_dop_gruzch_count]"
      assert_select "input#request_customer_dop_gruzch_summ", :name => "request[customer_dop_gruzch_summ]"
      assert_select "input#request_customer_total_summ", :name => "request[customer_total_summ]"
      assert_select "input#request_customer_summ_to_pay", :name => "request[customer_summ_to_pay]"
      assert_select "input#request_customer_invoice_number", :name => "request[customer_invoice_number]"
      assert_select "input#request_customer_payed_summ", :name => "request[customer_payed_summ]"
      assert_select "input#request_customer_prepayment", :name => "request[customer_prepayment]"
      assert_select "input#request_customer_payment_method_id", :name => "request[customer_payment_method_id]"
      assert_select "input#request_customer_payment_way_id", :name => "request[customer_payment_way_id]"
      assert_select "input#request_customer_maturity", :name => "request[customer_maturity]"
      assert_select "input#request_customer_payment_doc_id", :name => "request[customer_payment_doc_id]"
      assert_select "input#request_customer_documents_return_term", :name => "request[customer_documents_return_term]"
      assert_select "input#request_user_id", :name => "request[user_id]"
      assert_select "input#request_manager_fot", :name => "request[manager_fot]"
      assert_select "input#request_manager_percent", :name => "request[manager_percent]"
      assert_select "input#request_manager_premium", :name => "request[manager_premium]"
      assert_select "input#request_manager_total_summ", :name => "request[manager_total_summ]"
      assert_select "input#request_account_expenditure", :name => "request[account_expenditure]"
      assert_select "input#request_account_money", :name => "request[account_money]"
      assert_select "input#request_account_parish_summ", :name => "request[account_parish_summ]"
      assert_select "input#request_account_consumption_respect", :name => "request[account_consumption_respect]"
      assert_select "input#request_account_consumption_summ", :name => "request[account_consumption_summ]"
      assert_select "input#request_responsibility_transport_replacement_requirement", :name => "request[responsibility_transport_replacement_requirement]"
      assert_select "input#request_compensation_for_damage", :name => "request[compensation_for_damage]"
      assert_select "input#request_undeliver_transport_loading_city", :name => "request[undeliver_transport_loading_city]"
      assert_select "input#request_undeliver_transport_loading_intercity", :name => "request[undeliver_transport_loading_intercity]"
      assert_select "input#request_transport_late_loading_city", :name => "request[transport_late_loading_city]"
      assert_select "input#request_transport_late_loading_intercity", :name => "request[transport_late_loading_intercity]"
      assert_select "input#request_transport_late_destination_city", :name => "request[transport_late_destination_city]"
      assert_select "input#request_transport_late_destination_intercity", :name => "request[transport_late_destination_intercity]"
      assert_select "input#request_transport_refuse_loading_day_city", :name => "request[transport_refuse_loading_day_city]"
      assert_select "input#request_transport_refuse_loading_day_intercity", :name => "request[transport_refuse_loading_day_intercity]"
      assert_select "input#request_transport_idle_excessively_city", :name => "request[transport_idle_excessively_city]"
      assert_select "input#request_transport_idle_excessively_intercity", :name => "request[transport_idle_excessively_intercity]"
      assert_select "input#request_payment_late", :name => "request[payment_late]"
      assert_select "input#request_document_late", :name => "request[document_late]"
      assert_select "input#request_customer_responsibility_car_deny_price", :name => "request[customer_responsibility_car_deny_price]"
      assert_select "input#request_customer_responsibility_car_deny_summ", :name => "request[customer_responsibility_car_deny_summ]"
      assert_select "input#request_customer_responsibility_prostoy_count", :name => "request[customer_responsibility_prostoy_count]"
      assert_select "input#request_customer_responsibility_prostoy_price", :name => "request[customer_responsibility_prostoy_price]"
      assert_select "input#request_customer_responsibility_prostoy_summ", :name => "request[customer_responsibility_prostoy_summ]"
      assert_select "input#request_customer_responsibility_payment_late_count", :name => "request[customer_responsibility_payment_late_count]"
      assert_select "input#request_customer_responsibility_payment_late_price", :name => "request[customer_responsibility_payment_late_price]"
      assert_select "input#request_customer_responsibility_payment_late_summ", :name => "request[customer_responsibility_payment_late_summ]"
      assert_select "input#request_customer_responsibility_document_late_count", :name => "request[customer_responsibility_document_late_count]"
      assert_select "input#request_customer_responsibility_document_late_price", :name => "request[customer_responsibility_document_late_price]"
      assert_select "input#request_customer_responsibility_document_late_summ", :name => "request[customer_responsibility_document_late_summ]"
      assert_select "input#request_carrier_responsibility_car_deny_price", :name => "request[carrier_responsibility_car_deny_price]"
      assert_select "input#request_carrier_responsibility_car_deny_summ", :name => "request[carrier_responsibility_car_deny_summ]"
      assert_select "input#request_carrier_responsibility_late_count", :name => "request[carrier_responsibility_late_count]"
      assert_select "input#request_carrier_responsibility_late_price", :name => "request[carrier_responsibility_late_price]"
      assert_select "input#request_carrier_responsibility_late_summ", :name => "request[carrier_responsibility_late_summ]"
      assert_select "input#request_carrier_responsibility_delivery_late_count", :name => "request[carrier_responsibility_delivery_late_count]"
      assert_select "input#request_carrier_responsibility_delivery_late_price", :name => "request[carrier_responsibility_delivery_late_price]"
      assert_select "input#request_carrier_responsibility_delivery_late_summ", :name => "request[carrier_responsibility_delivery_late_summ]"
      assert_select "input#request_carrier_responsibility_document_late_count", :name => "request[carrier_responsibility_document_late_count]"
      assert_select "input#request_carrier_responsibility_document_late_price", :name => "request[carrier_responsibility_document_late_price]"
      assert_select "input#request_carrier_responsibility_document_late_summ", :name => "request[carrier_responsibility_document_late_summ]"
      assert_select "input#request_carrier_responsibility_summ", :name => "request[carrier_responsibility_summ]"
      assert_select "input#request_customer_responsibility_summ", :name => "request[customer_responsibility_summ]"
      assert_select "input#request_transport_idle_excessively_hours", :name => "request[transport_idle_excessively_hours]"
      assert_select "input#request_transport_late_loading_hours", :name => "request[transport_late_loading_hours]"
      assert_select "input#request_transport_late_destination_hours", :name => "request[transport_late_destination_hours]"
      assert_select "input#request_request_type", :name => "request[request_type]"
      assert_select "input#request_other_conditions", :name => "request[other_conditions]"
      assert_select "input#request_carrier_rate_total_summ", :name => "request[carrier_rate_total_summ]"
      assert_select "input#request_customer_rate_total_summ", :name => "request[customer_rate_total_summ]"
      assert_select "input#request_bill_id", :name => "request[bill_id]"
      assert_select "input#request_is_finished", :name => "request[is_finished]"
      assert_select "input#request_customer_payment_way_for_salary", :name => "request[customer_payment_way_for_salary]"
      assert_select "input#request_carrier_payment_way_for_salary", :name => "request[carrier_payment_way_for_salary]"
    end
  end
end
