Feature: Manage Requests
  In order to add request functionality
  As an manager and admin
  I want to create and manage requests


  @javascript
  Scenario: Create Valid Request (short version)
    Given I logined as manager
    And I am on the list of requests
    And I have all required fixtures up
    When I follow "addRequestLink"
    When I choose "request_type_contract_request"
    And I select "Продукты" from "request_cargo_classification_id"
    And I fill in "request_item" with "Макароны"
    And I fill in "request_volume" with "80"
    And I fill in "request_weight" with "5"
    And I fill in "request_temperature" with "от 5 до 10"
    And I fill in "length" with "1,8"
    And I fill in "width" with "2,8"
    And I fill in "height" with "3,8"
    And I fill in "request_evropallet" with "5"
    And I fill in "request_belts_count" with "4"
    And I fill in "request_crate_body" with "3"
    And I fill in "request_other_conditions" with "разгружать осторожно"
    And I check "request_loading_up"
    And I check "request_loading_side"
    And I select "CustomerCompany2" from "request_customer_company_id"
    And I select "CarrierCompany2" from "request_carrier_company_id"
    And I select "Иванов Семен Петрович" from "request_driver_id"
    And I select "Mercedes Рефрижератор 15.0" from "request_car_id"
    And I fill in "request_loading_point1_date" with "2011-12-04"
    And I fill in "request_loading_point1_time" with "18:00"
    And I fill in "request_loading_point1_address" with "la1"
    And I fill in "request_loading_point1_shipper" with "ls1"
    And I fill in "request_loading_point1_contact_person" with "lcp1"
    And I fill in "request_loading_point1_phone" with "lph1"
    And I fill in "request_loading_point1_phone_work" with "lpw1"
    And I fill in "request_unloading_point1_date" with "2011-12-05"
    And I fill in "request_unloading_point1_time" with "19:00"
    And I fill in "request_unloading_point1_address" with "ua1"
    And I fill in "request_unloading_point1_consignee" with "uc1"
    And I fill in "request_unloading_point1_contact_person" with "ucp1"
    And I fill in "request_unloading_point1_phone" with "uph1"
    And I fill in "request_unloading_point1_phone_work" with "upw1"
    And I fill in "customerRateSumm" with "5000"
    And I fill in "customerRateSverhPrice" with "700"
    And I click to ".carrierPayMethodButton"
    And I fill in "carrierRateHours" with "5"
    And I fill in "carrierRatePodachaHours" with "2"
    And I fill in "carrierRateHourPrice" with "800"
    And I fill in "carrierRateSverhPrice" with "1200"
    And I fill in "request_customer_dop_prab_price" with "100"
    And I fill in "request_customer_dop_dop_tochka_pogr_price" with "101"
    And I fill in "request_customer_dop_dop_tochka_razgr_price" with "102"
    And I fill in "request_customer_dop_rastentovka_price" with "103"
    And I fill in "request_customer_dop_pereg_price" with "104"
    And I fill in "request_customer_dop_night_stay_price" with "105"
    And I fill in "request_customer_dop_mezgorod_price" with "106"
    And I fill in "request_customer_dop_soprov_price" with "107"
    And I fill in "request_customer_dop_vozvr_price" with "108"
    And I fill in "request_customer_dop_negabarit_price" with "109"
    And I fill in "request_customer_dop_gruzch_price" with "110"
    And I fill in "request_carrier_dop_prab_price" with "200"
    And I fill in "request_carrier_dop_dop_tochka_pogr_price" with "201"
    And I fill in "request_carrier_dop_dop_tochka_razgr_price" with "202"
    And I fill in "request_carrier_dop_rastentovka_price" with "203"
    And I fill in "request_carrier_dop_pereg_price" with "204"
    And I fill in "request_carrier_dop_night_stay_price" with "205"
    And I fill in "request_carrier_dop_mezgorod_price" with "206"
    And I fill in "request_carrier_dop_soprov_price" with "207"
    And I fill in "request_carrier_dop_vozvr_price" with "208"
    And I fill in "request_carrier_dop_negabarit_price" with "209"
    And I fill in "request_carrier_dop_gruzch_price" with "210"
    And I select "Нал" from "request_customer_payment_method_id"
    And I select "На карту" from "request_customer_payment_way_id"
    And I fill in "request_customer_maturity" with "150"
    And I select "По копиям" from "request_customer_payment_doc_id"
    And I fill in "request_bill_id" with "22"
    And I select "Нал" from "request_carrier_payment_method_id"
    And I select "На карту" from "request_carrier_payment_way_id"
    And I fill in "request_carrier_maturity" with "150"
    And I select "По копиям" from "request_carrier_payment_doc_id"
    And I fill in "request_carrier_documents_return_term" with "3"
    And I fill in "request_carrier_bill_id" with "22"
    And I press "Сохранить заявку"
    And I should see "Открыть"


  @javascript
  Scenario: Create Valid Request
    Given I logined as manager
    And I am on the list of requests
    And I have all required fixtures up
    When I follow "addRequestLink"
    When I choose "request_type_contract_request"
    And I select "Продукты" from "request_cargo_classification_id"
    And I fill in "request_item" with "Макароны"
    And I fill in "request_volume" with "80"
    And I fill in "request_weight" with "5"
    And I fill in "request_temperature" with "от 5 до 10"
    And I fill in "length" with "1,8"
    And I fill in "width" with "2,8"
    And I fill in "height" with "3,8"
    And I fill in "request_evropallet" with "5"
    And I fill in "request_belts_count" with "4"
    And I fill in "request_crate_body" with "3"
    And I fill in "request_other_conditions" with "разгружать осторожно"
    And I check "request_loading_up"
    And I check "request_loading_side"
    And I select "CustomerCompany2" from "request_customer_company_id"
    And I select "CarrierCompany2" from "request_carrier_company_id"
    And I select "Иванов Семен Петрович" from "request_driver_id"
    And I select "Mercedes Рефрижератор 15.0" from "request_car_id"
    And I fill in "request_loading_point1_date" with "2011-12-04"
    And I fill in "request_loading_point1_time" with "18:00"
    And I fill in "request_loading_point1_address" with "la1"
    And I fill in "request_loading_point1_shipper" with "ls1"
    And I fill in "request_loading_point1_contact_person" with "lcp1"
    And I fill in "request_loading_point1_phone" with "lph1"
    And I fill in "request_loading_point1_phone_work" with "lpw1"
    And I fill in "request_unloading_point1_date" with "2011-12-05"
    And I fill in "request_unloading_point1_time" with "19:00"
    And I fill in "request_unloading_point1_address" with "ua1"
    And I fill in "request_unloading_point1_consignee" with "uc1"
    And I fill in "request_unloading_point1_contact_person" with "ucp1"
    And I fill in "request_unloading_point1_phone" with "uph1"
    And I fill in "request_unloading_point1_phone_work" with "upw1"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate2" with "2011-12-04"
    And I fill in "request[loading_point2][time]" with "18:00"
    And I fill in "loadingAddress2" with "la2"
    And I fill in "shipper2" with "ls2"
    And I fill in "loadingContactPerson2" with "lcp2"
    And I fill in "loadingContactPhone2" with "lph2"
    And I fill in "loadingContactPhoneWork2" with "lpw2"
    And I fill in "unloadingDate2" with "2011-12-05"
    And I fill in "request[loading_point2][time]" with "19:00"
    And I fill in "unloadingAddress2" with "ua2"
    And I fill in "consignee2" with "uc2"
    And I fill in "unloadingContactPerson2" with "ucp2"
    And I fill in "unloadingContactPhone2" with "uph2"
    And I fill in "unloadingContactPhoneWork2" with "upw2"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate3" with "2011-12-04"
    And I fill in "request[loading_point3][time]" with "18:00"
    And I fill in "loadingAddress3" with "la3"
    And I fill in "shipper3" with "ls3"
    And I fill in "loadingContactPerson3" with "lcp3"
    And I fill in "loadingContactPhone3" with "lph3"
    And I fill in "loadingContactPhoneWork3" with "lpw3"
    And I fill in "unloadingDate3" with "2011-12-05"
    And I fill in "request[loading_point3][time]" with "19:00"
    And I fill in "unloadingAddress3" with "ua3"
    And I fill in "consignee3" with "uc3"
    And I fill in "unloadingContactPerson3" with "ucp3"
    And I fill in "unloadingContactPhone3" with "uph3"
    And I fill in "unloadingContactPhoneWork3" with "upw3"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate4" with "2011-12-04"
    And I fill in "request[loading_point4][time]" with "18:00"
    And I fill in "loadingAddress4" with "la4"
    And I fill in "shipper4" with "ls4"
    And I fill in "loadingContactPerson4" with "lcp4"
    And I fill in "loadingContactPhone4" with "lph4"
    And I fill in "loadingContactPhoneWork4" with "lpw4"
    And I fill in "unloadingDate4" with "2011-12-05"
    And I fill in "request[loading_point4][time]" with "19:00"
    And I fill in "unloadingAddress4" with "ua4"
    And I fill in "consignee4" with "uc4"
    And I fill in "unloadingContactPerson4" with "ucp4"
    And I fill in "unloadingContactPhone4" with "uph4"
    And I fill in "unloadingContactPhoneWork4" with "upw4"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate5" with "2011-12-05"
    And I fill in "request[loading_point5][time]" with "18:00"
    And I fill in "loadingAddress5" with "la5"
    And I fill in "shipper5" with "ls5"
    And I fill in "loadingContactPerson5" with "lcp5"
    And I fill in "loadingContactPhone5" with "lph5"
    And I fill in "loadingContactPhoneWork5" with "lpw5"
    And I fill in "unloadingDate5" with "2011-12-05"
    And I fill in "request[loading_point5][time]" with "19:00"
    And I fill in "unloadingAddress5" with "ua5"
    And I fill in "consignee5" with "uc5"
    And I fill in "unloadingContactPerson5" with "ucp5"
    And I fill in "unloadingContactPhone5" with "uph5"
    And I fill in "unloadingContactPhoneWork5" with "upw5"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate6" with "2011-12-06"
    And I fill in "request[loading_point6][time]" with "18:00"
    And I fill in "loadingAddress6" with "la6"
    And I fill in "shipper6" with "ls6"
    And I fill in "loadingContactPerson6" with "lcp6"
    And I fill in "loadingContactPhone6" with "lph6"
    And I fill in "loadingContactPhoneWork6" with "lpw6"
    And I fill in "unloadingDate6" with "2011-12-06"
    And I fill in "request[loading_point6][time]" with "19:00"
    And I fill in "unloadingAddress6" with "ua6"
    And I fill in "consignee6" with "uc6"
    And I fill in "unloadingContactPerson6" with "ucp6"
    And I fill in "unloadingContactPhone6" with "uph6"
    And I fill in "unloadingContactPhoneWork6" with "upw6"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate7" with "2011-12-07"
    And I fill in "request[loading_point7][time]" with "18:00"
    And I fill in "loadingAddress7" with "la7"
    And I fill in "shipper7" with "ls7"
    And I fill in "loadingContactPerson7" with "lcp7"
    And I fill in "loadingContactPhone7" with "lph7"
    And I fill in "loadingContactPhoneWork7" with "lpw7"
    And I fill in "unloadingDate7" with "2011-12-07"
    And I fill in "request[loading_point7][time]" with "19:00"
    And I fill in "unloadingAddress7" with "ua7"
    And I fill in "consignee7" with "uc7"
    And I fill in "unloadingContactPerson7" with "ucp7"
    And I fill in "unloadingContactPhone7" with "uph7"
    And I fill in "unloadingContactPhoneWork7" with "upw7"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate8" with "2011-12-08"
    And I fill in "request[loading_point8][time]" with "18:00"
    And I fill in "loadingAddress8" with "la8"
    And I fill in "shipper8" with "ls8"
    And I fill in "loadingContactPerson8" with "lcp8"
    And I fill in "loadingContactPhone8" with "lph8"
    And I fill in "loadingContactPhoneWork8" with "lpw8"
    And I fill in "unloadingDate8" with "2011-12-08"
    And I fill in "request[loading_point8][time]" with "19:00"
    And I fill in "unloadingAddress8" with "ua8"
    And I fill in "consignee8" with "uc8"
    And I fill in "unloadingContactPerson8" with "ucp8"
    And I fill in "unloadingContactPhone8" with "uph8"
    And I fill in "unloadingContactPhoneWork8" with "upw8"
    And I click to "#loadingButton p"
    And I click to "#unloadingButton p"
    And I fill in "loadingDate9" with "2011-12-09"
    And I fill in "request[loading_point9][time]" with "19:00"
    And I fill in "loadingAddress9" with "la9"
    And I fill in "shipper9" with "ls9"
    And I fill in "loadingContactPerson9" with "lcp9"
    And I fill in "loadingContactPhone9" with "lph9"
    And I fill in "loadingContactPhoneWork9" with "lpw9"
    And I fill in "unloadingDate9" with "2011-12-09"
    And I fill in "request[loading_point9][time]" with "19:00"
    And I fill in "unloadingAddress9" with "ua9"
    And I fill in "consignee9" with "uc9"
    And I fill in "unloadingContactPerson9" with "ucp9"
    And I fill in "unloadingContactPhone9" with "uph9"
    And I fill in "unloadingContactPhoneWork9" with "upw9"
