require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CarTonnagesController do

  # This should return the minimal set of attributes required to create a valid
  # CarTonnage. As you add validations to CarTonnage, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all car_tonnages as @car_tonnages" do
      car_tonnage = CarTonnage.create! valid_attributes
      get :index
      assigns(:car_tonnages).should eq([car_tonnage])
    end
  end

  describe "GET show" do
    it "assigns the requested car_tonnage as @car_tonnage" do
      car_tonnage = CarTonnage.create! valid_attributes
      get :show, :id => car_tonnage.id.to_s
      assigns(:car_tonnage).should eq(car_tonnage)
    end
  end

  describe "GET new" do
    it "assigns a new car_tonnage as @car_tonnage" do
      get :new
      assigns(:car_tonnage).should be_a_new(CarTonnage)
    end
  end

  describe "GET edit" do
    it "assigns the requested car_tonnage as @car_tonnage" do
      car_tonnage = CarTonnage.create! valid_attributes
      get :edit, :id => car_tonnage.id.to_s
      assigns(:car_tonnage).should eq(car_tonnage)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CarTonnage" do
        expect {
          post :create, :car_tonnage => valid_attributes
        }.to change(CarTonnage, :count).by(1)
      end

      it "assigns a newly created car_tonnage as @car_tonnage" do
        post :create, :car_tonnage => valid_attributes
        assigns(:car_tonnage).should be_a(CarTonnage)
        assigns(:car_tonnage).should be_persisted
      end

      it "redirects to the created car_tonnage" do
        post :create, :car_tonnage => valid_attributes
        response.should redirect_to(CarTonnage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved car_tonnage as @car_tonnage" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarTonnage.any_instance.stub(:save).and_return(false)
        post :create, :car_tonnage => {}
        assigns(:car_tonnage).should be_a_new(CarTonnage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CarTonnage.any_instance.stub(:save).and_return(false)
        post :create, :car_tonnage => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested car_tonnage" do
        car_tonnage = CarTonnage.create! valid_attributes
        # Assuming there are no other car_tonnages in the database, this
        # specifies that the CarTonnage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CarTonnage.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => car_tonnage.id, :car_tonnage => {'these' => 'params'}
      end

      it "assigns the requested car_tonnage as @car_tonnage" do
        car_tonnage = CarTonnage.create! valid_attributes
        put :update, :id => car_tonnage.id, :car_tonnage => valid_attributes
        assigns(:car_tonnage).should eq(car_tonnage)
      end

      it "redirects to the car_tonnage" do
        car_tonnage = CarTonnage.create! valid_attributes
        put :update, :id => car_tonnage.id, :car_tonnage => valid_attributes
        response.should redirect_to(car_tonnage)
      end
    end

    describe "with invalid params" do
      it "assigns the car_tonnage as @car_tonnage" do
        car_tonnage = CarTonnage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarTonnage.any_instance.stub(:save).and_return(false)
        put :update, :id => car_tonnage.id.to_s, :car_tonnage => {}
        assigns(:car_tonnage).should eq(car_tonnage)
      end

      it "re-renders the 'edit' template" do
        car_tonnage = CarTonnage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CarTonnage.any_instance.stub(:save).and_return(false)
        put :update, :id => car_tonnage.id.to_s, :car_tonnage => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested car_tonnage" do
      car_tonnage = CarTonnage.create! valid_attributes
      expect {
        delete :destroy, :id => car_tonnage.id.to_s
      }.to change(CarTonnage, :count).by(-1)
    end

    it "redirects to the car_tonnages list" do
      car_tonnage = CarTonnage.create! valid_attributes
      delete :destroy, :id => car_tonnage.id.to_s
      response.should redirect_to(car_tonnages_url)
    end
  end

end
