require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CargoClassificationsController do

  # This should return the minimal set of attributes required to create a valid
  # CargoClassification. As you add validations to CargoClassification, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all cargo_classifications as @cargo_classifications" do
      cargo_classification = CargoClassification.create! valid_attributes
      get :index
      assigns(:cargo_classifications).should eq([cargo_classification])
    end
  end

  describe "GET show" do
    it "assigns the requested cargo_classification as @cargo_classification" do
      cargo_classification = CargoClassification.create! valid_attributes
      get :show, :id => cargo_classification.id.to_s
      assigns(:cargo_classification).should eq(cargo_classification)
    end
  end

  describe "GET new" do
    it "assigns a new cargo_classification as @cargo_classification" do
      get :new
      assigns(:cargo_classification).should be_a_new(CargoClassification)
    end
  end

  describe "GET edit" do
    it "assigns the requested cargo_classification as @cargo_classification" do
      cargo_classification = CargoClassification.create! valid_attributes
      get :edit, :id => cargo_classification.id.to_s
      assigns(:cargo_classification).should eq(cargo_classification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CargoClassification" do
        expect {
          post :create, :cargo_classification => valid_attributes
        }.to change(CargoClassification, :count).by(1)
      end

      it "assigns a newly created cargo_classification as @cargo_classification" do
        post :create, :cargo_classification => valid_attributes
        assigns(:cargo_classification).should be_a(CargoClassification)
        assigns(:cargo_classification).should be_persisted
      end

      it "redirects to the created cargo_classification" do
        post :create, :cargo_classification => valid_attributes
        response.should redirect_to(CargoClassification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved cargo_classification as @cargo_classification" do
        # Trigger the behavior that occurs when invalid params are submitted
        CargoClassification.any_instance.stub(:save).and_return(false)
        post :create, :cargo_classification => {}
        assigns(:cargo_classification).should be_a_new(CargoClassification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CargoClassification.any_instance.stub(:save).and_return(false)
        post :create, :cargo_classification => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested cargo_classification" do
        cargo_classification = CargoClassification.create! valid_attributes
        # Assuming there are no other cargo_classifications in the database, this
        # specifies that the CargoClassification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CargoClassification.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => cargo_classification.id, :cargo_classification => {'these' => 'params'}
      end

      it "assigns the requested cargo_classification as @cargo_classification" do
        cargo_classification = CargoClassification.create! valid_attributes
        put :update, :id => cargo_classification.id, :cargo_classification => valid_attributes
        assigns(:cargo_classification).should eq(cargo_classification)
      end

      it "redirects to the cargo_classification" do
        cargo_classification = CargoClassification.create! valid_attributes
        put :update, :id => cargo_classification.id, :cargo_classification => valid_attributes
        response.should redirect_to(cargo_classification)
      end
    end

    describe "with invalid params" do
      it "assigns the cargo_classification as @cargo_classification" do
        cargo_classification = CargoClassification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CargoClassification.any_instance.stub(:save).and_return(false)
        put :update, :id => cargo_classification.id.to_s, :cargo_classification => {}
        assigns(:cargo_classification).should eq(cargo_classification)
      end

      it "re-renders the 'edit' template" do
        cargo_classification = CargoClassification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CargoClassification.any_instance.stub(:save).and_return(false)
        put :update, :id => cargo_classification.id.to_s, :cargo_classification => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested cargo_classification" do
      cargo_classification = CargoClassification.create! valid_attributes
      expect {
        delete :destroy, :id => cargo_classification.id.to_s
      }.to change(CargoClassification, :count).by(-1)
    end

    it "redirects to the cargo_classifications list" do
      cargo_classification = CargoClassification.create! valid_attributes
      delete :destroy, :id => cargo_classification.id.to_s
      response.should redirect_to(cargo_classifications_url)
    end
  end

end
