require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CompanyFacesController do

  # This should return the minimal set of attributes required to create a valid
  # CompanyFace. As you add validations to CompanyFace, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all company_faces as @company_faces" do
      company_face = CompanyFace.create! valid_attributes
      get :index
      assigns(:company_faces).should eq([company_face])
    end
  end

  describe "GET show" do
    it "assigns the requested company_face as @company_face" do
      company_face = CompanyFace.create! valid_attributes
      get :show, :id => company_face.id.to_s
      assigns(:company_face).should eq(company_face)
    end
  end

  describe "GET new" do
    it "assigns a new company_face as @company_face" do
      get :new
      assigns(:company_face).should be_a_new(CompanyFace)
    end
  end

  describe "GET edit" do
    it "assigns the requested company_face as @company_face" do
      company_face = CompanyFace.create! valid_attributes
      get :edit, :id => company_face.id.to_s
      assigns(:company_face).should eq(company_face)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CompanyFace" do
        expect {
          post :create, :company_face => valid_attributes
        }.to change(CompanyFace, :count).by(1)
      end

      it "assigns a newly created company_face as @company_face" do
        post :create, :company_face => valid_attributes
        assigns(:company_face).should be_a(CompanyFace)
        assigns(:company_face).should be_persisted
      end

      it "redirects to the created company_face" do
        post :create, :company_face => valid_attributes
        response.should redirect_to(CompanyFace.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved company_face as @company_face" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyFace.any_instance.stub(:save).and_return(false)
        post :create, :company_face => {}
        assigns(:company_face).should be_a_new(CompanyFace)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyFace.any_instance.stub(:save).and_return(false)
        post :create, :company_face => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested company_face" do
        company_face = CompanyFace.create! valid_attributes
        # Assuming there are no other company_faces in the database, this
        # specifies that the CompanyFace created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CompanyFace.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => company_face.id, :company_face => {'these' => 'params'}
      end

      it "assigns the requested company_face as @company_face" do
        company_face = CompanyFace.create! valid_attributes
        put :update, :id => company_face.id, :company_face => valid_attributes
        assigns(:company_face).should eq(company_face)
      end

      it "redirects to the company_face" do
        company_face = CompanyFace.create! valid_attributes
        put :update, :id => company_face.id, :company_face => valid_attributes
        response.should redirect_to(company_face)
      end
    end

    describe "with invalid params" do
      it "assigns the company_face as @company_face" do
        company_face = CompanyFace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyFace.any_instance.stub(:save).and_return(false)
        put :update, :id => company_face.id.to_s, :company_face => {}
        assigns(:company_face).should eq(company_face)
      end

      it "re-renders the 'edit' template" do
        company_face = CompanyFace.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CompanyFace.any_instance.stub(:save).and_return(false)
        put :update, :id => company_face.id.to_s, :company_face => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested company_face" do
      company_face = CompanyFace.create! valid_attributes
      expect {
        delete :destroy, :id => company_face.id.to_s
      }.to change(CompanyFace, :count).by(-1)
    end

    it "redirects to the company_faces list" do
      company_face = CompanyFace.create! valid_attributes
      delete :destroy, :id => company_face.id.to_s
      response.should redirect_to(company_faces_url)
    end
  end

end
