require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomerCompaniesController do

  # This should return the minimal set of attributes required to create a valid
  # CustomerCompany. As you add validations to CustomerCompany, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all customer_companies as @customer_companies" do
      customer_company = CustomerCompany.create! valid_attributes
      get :index
      assigns(:customer_companies).should eq([customer_company])
    end
  end

  describe "GET show" do
    it "assigns the requested customer_company as @customer_company" do
      customer_company = CustomerCompany.create! valid_attributes
      get :show, :id => customer_company.id.to_s
      assigns(:customer_company).should eq(customer_company)
    end
  end

  describe "GET new" do
    it "assigns a new customer_company as @customer_company" do
      get :new
      assigns(:customer_company).should be_a_new(CustomerCompany)
    end
  end

  describe "GET edit" do
    it "assigns the requested customer_company as @customer_company" do
      customer_company = CustomerCompany.create! valid_attributes
      get :edit, :id => customer_company.id.to_s
      assigns(:customer_company).should eq(customer_company)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomerCompany" do
        expect {
          post :create, :customer_company => valid_attributes
        }.to change(CustomerCompany, :count).by(1)
      end

      it "assigns a newly created customer_company as @customer_company" do
        post :create, :customer_company => valid_attributes
        assigns(:customer_company).should be_a(CustomerCompany)
        assigns(:customer_company).should be_persisted
      end

      it "redirects to the created customer_company" do
        post :create, :customer_company => valid_attributes
        response.should redirect_to(CustomerCompany.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customer_company as @customer_company" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCompany.any_instance.stub(:save).and_return(false)
        post :create, :customer_company => {}
        assigns(:customer_company).should be_a_new(CustomerCompany)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCompany.any_instance.stub(:save).and_return(false)
        post :create, :customer_company => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customer_company" do
        customer_company = CustomerCompany.create! valid_attributes
        # Assuming there are no other customer_companies in the database, this
        # specifies that the CustomerCompany created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomerCompany.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => customer_company.id, :customer_company => {'these' => 'params'}
      end

      it "assigns the requested customer_company as @customer_company" do
        customer_company = CustomerCompany.create! valid_attributes
        put :update, :id => customer_company.id, :customer_company => valid_attributes
        assigns(:customer_company).should eq(customer_company)
      end

      it "redirects to the customer_company" do
        customer_company = CustomerCompany.create! valid_attributes
        put :update, :id => customer_company.id, :customer_company => valid_attributes
        response.should redirect_to(customer_company)
      end
    end

    describe "with invalid params" do
      it "assigns the customer_company as @customer_company" do
        customer_company = CustomerCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCompany.any_instance.stub(:save).and_return(false)
        put :update, :id => customer_company.id.to_s, :customer_company => {}
        assigns(:customer_company).should eq(customer_company)
      end

      it "re-renders the 'edit' template" do
        customer_company = CustomerCompany.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerCompany.any_instance.stub(:save).and_return(false)
        put :update, :id => customer_company.id.to_s, :customer_company => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customer_company" do
      customer_company = CustomerCompany.create! valid_attributes
      expect {
        delete :destroy, :id => customer_company.id.to_s
      }.to change(CustomerCompany, :count).by(-1)
    end

    it "redirects to the customer_companies list" do
      customer_company = CustomerCompany.create! valid_attributes
      delete :destroy, :id => customer_company.id.to_s
      response.should redirect_to(customer_companies_url)
    end
  end

end
