require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe OutcomeSectionsController do

  # This should return the minimal set of attributes required to create a valid
  # OutcomeSection. As you add validations to OutcomeSection, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all outcome_sections as @outcome_sections" do
      outcome_section = OutcomeSection.create! valid_attributes
      get :index
      assigns(:outcome_sections).should eq([outcome_section])
    end
  end

  describe "GET show" do
    it "assigns the requested outcome_section as @outcome_section" do
      outcome_section = OutcomeSection.create! valid_attributes
      get :show, :id => outcome_section.id.to_s
      assigns(:outcome_section).should eq(outcome_section)
    end
  end

  describe "GET new" do
    it "assigns a new outcome_section as @outcome_section" do
      get :new
      assigns(:outcome_section).should be_a_new(OutcomeSection)
    end
  end

  describe "GET edit" do
    it "assigns the requested outcome_section as @outcome_section" do
      outcome_section = OutcomeSection.create! valid_attributes
      get :edit, :id => outcome_section.id.to_s
      assigns(:outcome_section).should eq(outcome_section)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new OutcomeSection" do
        expect {
          post :create, :outcome_section => valid_attributes
        }.to change(OutcomeSection, :count).by(1)
      end

      it "assigns a newly created outcome_section as @outcome_section" do
        post :create, :outcome_section => valid_attributes
        assigns(:outcome_section).should be_a(OutcomeSection)
        assigns(:outcome_section).should be_persisted
      end

      it "redirects to the created outcome_section" do
        post :create, :outcome_section => valid_attributes
        response.should redirect_to(OutcomeSection.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved outcome_section as @outcome_section" do
        # Trigger the behavior that occurs when invalid params are submitted
        OutcomeSection.any_instance.stub(:save).and_return(false)
        post :create, :outcome_section => {}
        assigns(:outcome_section).should be_a_new(OutcomeSection)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        OutcomeSection.any_instance.stub(:save).and_return(false)
        post :create, :outcome_section => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested outcome_section" do
        outcome_section = OutcomeSection.create! valid_attributes
        # Assuming there are no other outcome_sections in the database, this
        # specifies that the OutcomeSection created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        OutcomeSection.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => outcome_section.id, :outcome_section => {'these' => 'params'}
      end

      it "assigns the requested outcome_section as @outcome_section" do
        outcome_section = OutcomeSection.create! valid_attributes
        put :update, :id => outcome_section.id, :outcome_section => valid_attributes
        assigns(:outcome_section).should eq(outcome_section)
      end

      it "redirects to the outcome_section" do
        outcome_section = OutcomeSection.create! valid_attributes
        put :update, :id => outcome_section.id, :outcome_section => valid_attributes
        response.should redirect_to(outcome_section)
      end
    end

    describe "with invalid params" do
      it "assigns the outcome_section as @outcome_section" do
        outcome_section = OutcomeSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OutcomeSection.any_instance.stub(:save).and_return(false)
        put :update, :id => outcome_section.id.to_s, :outcome_section => {}
        assigns(:outcome_section).should eq(outcome_section)
      end

      it "re-renders the 'edit' template" do
        outcome_section = OutcomeSection.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        OutcomeSection.any_instance.stub(:save).and_return(false)
        put :update, :id => outcome_section.id.to_s, :outcome_section => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested outcome_section" do
      outcome_section = OutcomeSection.create! valid_attributes
      expect {
        delete :destroy, :id => outcome_section.id.to_s
      }.to change(OutcomeSection, :count).by(-1)
    end

    it "redirects to the outcome_sections list" do
      outcome_section = OutcomeSection.create! valid_attributes
      delete :destroy, :id => outcome_section.id.to_s
      response.should redirect_to(outcome_sections_url)
    end
  end

end
